#include "unity.h"
#include "test_helpers.h"

void setUp(void) {}
void tearDown(void) {}

/* attribute_test.c */
void test_attr_set_and_get_float(void);
void test_attr_set_and_get_int(void);
void test_attr_set_and_get_bool(void);
void test_attr_set_and_get_string(void);
void test_attr_overwrite_existing(void);
void test_attr_get_missing_returns_fallback(void);
void test_attr_push_many_entries(void);
void test_attr_type_change(void);
void test_attr_scoped_instance_overrides_blueprint(void);
void test_attr_multiple_types(void);
void test_attr_get_scoped_float(void);
void test_attr_get_scoped_int(void);
void test_attr_get_scoped_bool(void);
void test_attr_get_scoped_string(void);
void test_attr_get_scoped_null_blueprint(void);

/* blueprint_test.c */
void test_blueprint_load_single(void);
void test_blueprint_load_multiple(void);
void test_blueprint_find(void);
void test_blueprint_skip_nameless(void);
void test_blueprint_no_blueprints_section(void);
void test_blueprint_custom_attrs(void);
void test_blueprint_health_parsed(void);
void test_blueprint_extends(void);
void test_blueprint_extends_chain(void);
void test_blueprint_child_parsed(void);
void test_blueprint_multiple_children(void);
void test_blueprint_child_no_tag(void);
void test_blueprint_child_default_offset(void);

/* entity_test.c */
void test_entity_init_from_blueprint(void);
void test_entity_get_attr_from_blueprint(void);
void test_entity_instance_overrides_blueprint(void);
void test_entity_get_missing_attr(void);
void test_entity_int_float_coercion(void);
void test_entity_no_blueprint(void);
void test_entity_solid_from_collision(void);
void test_entity_find_by_tag_self(void);
void test_entity_find_by_tag_parent(void);
void test_entity_find_by_tag_parent_of_root(void);
void test_entity_find_by_tag_root(void);
void test_entity_find_by_tag_custom(void);
void test_entity_find_by_tag_not_found(void);
void test_entity_is_visible_standalone(void);
void test_entity_is_visible_parent_hidden(void);
void test_entity_is_visible_both_visible(void);
void test_entity_is_active_parent_inactive(void);
void test_entity_is_active_both_active(void);

/* game_test.c */
void test_game_init_defaults(void);
void test_game_update_increments_frame(void);
void test_game_update_accumulates_elapsed(void);
void test_game_update_player_moves_right(void);
void test_game_update_player_moves_left(void);
void test_game_update_no_input_no_movement(void);
void test_game_player_clamps_to_bounds(void);
void test_game_player_collision_from_blueprint(void);
void test_game_update_resolves_obstacle_collision(void);

/* level_test.c */
void test_level_load_first(void);
void test_level_load_by_name(void);
void test_level_load_nonexistent(void);
void test_level_entity_positions(void);
void test_level_entity_source_rects(void);
void test_level_child_entities_instantiated(void);
void test_level_child_entity_positions(void);
void test_level_child_entity_tags(void);
void test_level_nested_children(void);

/* integration_test.c */
void test_integration_load_gamedata(void);
void test_integration_load_specific_level(void);
void test_integration_walk_and_collide(void);
void test_integration_walk_freely(void);
void test_integration_boundary_all_directions(void);
void test_integration_player_entity_spawns(void);
void test_integration_on_spawn_trigger_fires_on_load(void);
void test_integration_enter_trigger_fires_on_overlap(void);
void test_integration_enter_trigger_fires_only_once(void);

/* toml_str_test.c */
void test_toml_str_content_is_copied(void);
void test_toml_str_datum_nulled_after_call(void);

/* toml_emitter_test.c */
void test_toml_emit_blueprints(void);
void test_toml_emit_level_with_entities(void);
void test_toml_emit_round_trip(void);
void test_toml_emit_buffer_too_small(void);
void test_toml_emit_no_music(void);
void test_toml_emit_blueprint_children(void);
void test_toml_emit_skips_child_entities(void);
void test_toml_emit_custom_attrs(void);
void test_toml_emit_health(void);
void test_toml_emit_rules(void);

/* rule_test.c */
void test_flag_set_and_get(void);
void test_flag_clear(void);
void test_flag_unset_returns_false(void);
void test_flag_set_idempotent(void);
void test_flag_clear_nonexistent(void);
void test_trigger_parse_interact(void);
void test_trigger_parse_enter(void);
void test_trigger_parse_on_spawn(void);
void test_trigger_parse_event(void);
void test_trigger_parse_attr_changed(void);
void test_trigger_parse_unknown(void);
void test_condition_parse_flag(void);
void test_condition_parse_not_flag(void);
void test_condition_parse_attr_truthy(void);
void test_condition_parse_attr_short_form(void);
void test_condition_parse_not_attr(void);
void test_condition_parse_attr_less_than(void);
void test_condition_parse_attr_greater_than(void);
void test_condition_parse_attr_equals(void);
void test_condition_parse_has_item(void);
void test_condition_parse_unknown(void);
void test_action_parse_set_flag(void);
void test_action_parse_clear_flag(void);
void test_action_parse_set_attr(void);
void test_action_parse_add_attr(void);
void test_action_parse_toggle_attr(void);
void test_action_parse_destroy(void);
void test_action_parse_fire_event(void);
void test_action_parse_unknown(void);
void test_trigger_matches_simple(void);
void test_trigger_no_match_different_type(void);
void test_trigger_matches_event_with_argument(void);
void test_trigger_no_match_event_wrong_argument(void);
void test_condition_flag_true(void);
void test_condition_flag_false(void);
void test_condition_not_flag(void);
void test_condition_attr_truthy(void);
void test_condition_attr_falsy(void);
void test_condition_attr_missing(void);
void test_condition_attr_less_than(void);
void test_condition_attr_greater_than(void);
void test_condition_and_logic_all_pass(void);
void test_condition_and_logic_one_fails(void);
void test_action_set_flag_executes(void);
void test_action_clear_flag_executes(void);
void test_action_set_attr_bool(void);
void test_action_set_attr_int(void);
void test_action_add_attr(void);
void test_action_toggle_attr(void);
void test_action_destroy(void);
void test_action_fire_event_queues(void);
void test_action_execution_order(void);
void test_rules_parse_from_toml(void);
void test_rules_parse_no_rules(void);
void test_rules_parse_multiple_rules(void);
void test_evaluate_interact_sets_flag(void);
void test_evaluate_condition_blocks_action(void);
void test_evaluate_fire_event_cascading(void);
void test_integration_interact_rule(void);
void test_integration_condition_blocks_interact(void);
void test_integration_for_each_no_bind_iterates_all_entities(void);
void test_integration_for_each_condition_filter(void);
void test_integration_for_each_bind_mode(void);
void test_integration_subroutine_call(void);
void test_integration_subroutine_inherits_self(void);
void test_integration_subroutine_missing_is_soft_fail(void);
void test_integration_timer_oneshot_fires_once(void);
void test_integration_timer_periodic_fires_repeatedly(void);
void test_integration_timer_destroy_cancels(void);
void test_integration_on_destroy_fires(void);
void test_integration_defeat_fires_when_health_drops_to_zero(void);
void test_integration_collide_fires_on_overlap(void);
void test_var_set_local(void);
void test_var_set_global(void);
void test_var_condition_truthy(void);
void test_var_condition_falsy_when_unset(void);
void test_var_substitution_in_set_attr(void);
void test_local_var_scoped_per_rule(void);

/* editor_test.c */
void test_editor_radial_dead_zone_returns_negative_one(void);
void test_editor_radial_stick_up_four_items(void);
void test_editor_radial_stick_right_four_items(void);
void test_editor_radial_stick_down_four_items(void);
void test_editor_radial_stick_left_four_items(void);
void test_editor_radial_label_grab(void);
void test_editor_radial_label_delete(void);
void test_editor_radial_label_out_of_bounds(void);
void test_editor_word_builder_append_to_empty(void);
void test_editor_word_builder_append_with_underscore(void);
void test_editor_word_builder_append_overflow_noop(void);
void test_editor_word_builder_append_multiple(void);
void test_editor_word_builder_pop_last_word(void);
void test_editor_word_builder_pop_single_word(void);
void test_editor_word_builder_pop_empty_noop(void);
void test_editor_word_builder_total_count_no_blueprints(void);
void test_editor_word_builder_total_count_with_blueprints(void);
void test_editor_word_builder_item_zero_is_done(void);
void test_editor_word_builder_item_first_builtin(void);
void test_editor_word_builder_item_blueprint_name(void);
void test_editor_word_builder_item_negative_index(void);
void test_editor_place_visible_count_known_height(void);
void test_editor_place_visible_count_small_height(void);
void test_editor_total_attr_count_instance_only(void);
void test_editor_total_attr_count_with_blueprint(void);
void test_editor_is_blueprint_attr_false_for_instance(void);
void test_editor_is_blueprint_attr_true_for_blueprint(void);
void test_editor_find_nearest_single_entity(void);
void test_editor_find_nearest_closer_wins(void);
void test_editor_find_nearest_skips_children(void);
void test_editor_find_nearest_empty_level(void);
void test_editor_entity_outline_rect_with_collision(void);
void test_editor_entity_outline_rect_without_collision(void);
void test_editor_find_blueprint_by_name_found(void);
void test_editor_find_blueprint_by_name_not_found(void);
void test_editor_find_blueprint_by_name_empty_table(void);
void test_editor_mark_deleted_root_marks_child(void);
void test_editor_mark_deleted_chain(void);
void test_editor_mark_deleted_sibling_untouched(void);
void test_editor_apply_attr_delta_int(void);
void test_editor_apply_attr_delta_float(void);
void test_editor_apply_attr_delta_null_attr_no_crash(void);
void test_editor_attr_at_display_index_instance(void);
void test_editor_attr_at_display_index_blueprint(void);
void test_editor_attr_at_display_index_out_of_range(void);
void test_editor_toggle_pressed_key(void);
void test_editor_toggle_pressed_gamepad(void);
void test_editor_toggle_pressed_neither(void);
void test_editor_read_value_delta_no_input(void);
void test_editor_read_value_delta_large_minus(void);
void test_editor_read_value_delta_large_plus(void);
void test_editor_read_value_delta_huge_minus(void);
void test_editor_read_value_delta_combined(void);
void test_editor_read_held_dir_left_key(void);
void test_editor_read_held_dir_right_gamepad(void);
void test_editor_read_held_dir_none(void);
void test_editor_word_builder_nav_up(void);
void test_editor_word_builder_nav_up_clamped(void);
void test_editor_word_builder_nav_down(void);
void test_editor_word_builder_nav_down_clamped(void);
void test_editor_word_builder_nav_page_up(void);
void test_editor_word_builder_nav_page_down(void);

int main(void)
{
    test_helpers_init();
    UNITY_BEGIN();

    RUN_TEST(test_attr_set_and_get_float);
    RUN_TEST(test_attr_set_and_get_int);
    RUN_TEST(test_attr_set_and_get_bool);
    RUN_TEST(test_attr_set_and_get_string);
    RUN_TEST(test_attr_overwrite_existing);
    RUN_TEST(test_attr_get_missing_returns_fallback);
    RUN_TEST(test_attr_push_many_entries);
    RUN_TEST(test_attr_type_change);
    RUN_TEST(test_attr_scoped_instance_overrides_blueprint);
    RUN_TEST(test_attr_multiple_types);
    RUN_TEST(test_attr_get_scoped_float);
    RUN_TEST(test_attr_get_scoped_int);
    RUN_TEST(test_attr_get_scoped_bool);
    RUN_TEST(test_attr_get_scoped_string);
    RUN_TEST(test_attr_get_scoped_null_blueprint);

    RUN_TEST(test_blueprint_load_single);
    RUN_TEST(test_blueprint_load_multiple);
    RUN_TEST(test_blueprint_find);
    RUN_TEST(test_blueprint_skip_nameless);
    RUN_TEST(test_blueprint_no_blueprints_section);
    RUN_TEST(test_blueprint_custom_attrs);
    RUN_TEST(test_blueprint_health_parsed);
    RUN_TEST(test_blueprint_extends);
    RUN_TEST(test_blueprint_extends_chain);
    RUN_TEST(test_blueprint_child_parsed);
    RUN_TEST(test_blueprint_multiple_children);
    RUN_TEST(test_blueprint_child_no_tag);
    RUN_TEST(test_blueprint_child_default_offset);

    RUN_TEST(test_entity_init_from_blueprint);
    RUN_TEST(test_entity_get_attr_from_blueprint);
    RUN_TEST(test_entity_instance_overrides_blueprint);
    RUN_TEST(test_entity_get_missing_attr);
    RUN_TEST(test_entity_int_float_coercion);
    RUN_TEST(test_entity_no_blueprint);
    RUN_TEST(test_entity_solid_from_collision);
    RUN_TEST(test_entity_find_by_tag_self);
    RUN_TEST(test_entity_find_by_tag_parent);
    RUN_TEST(test_entity_find_by_tag_parent_of_root);
    RUN_TEST(test_entity_find_by_tag_root);
    RUN_TEST(test_entity_find_by_tag_custom);
    RUN_TEST(test_entity_find_by_tag_not_found);
    RUN_TEST(test_entity_is_visible_standalone);
    RUN_TEST(test_entity_is_visible_parent_hidden);
    RUN_TEST(test_entity_is_visible_both_visible);
    RUN_TEST(test_entity_is_active_parent_inactive);
    RUN_TEST(test_entity_is_active_both_active);

    RUN_TEST(test_game_init_defaults);
    RUN_TEST(test_game_update_increments_frame);
    RUN_TEST(test_game_update_accumulates_elapsed);
    RUN_TEST(test_game_update_player_moves_right);
    RUN_TEST(test_game_update_player_moves_left);
    RUN_TEST(test_game_update_no_input_no_movement);
    RUN_TEST(test_game_player_clamps_to_bounds);
    RUN_TEST(test_game_player_collision_from_blueprint);
    RUN_TEST(test_game_update_resolves_obstacle_collision);

    RUN_TEST(test_integration_load_gamedata);
    RUN_TEST(test_integration_load_specific_level);
    RUN_TEST(test_integration_walk_and_collide);
    RUN_TEST(test_integration_walk_freely);
    RUN_TEST(test_integration_boundary_all_directions);
    RUN_TEST(test_integration_player_entity_spawns);
    RUN_TEST(test_integration_on_spawn_trigger_fires_on_load);
    RUN_TEST(test_integration_enter_trigger_fires_on_overlap);
    RUN_TEST(test_integration_enter_trigger_fires_only_once);

    RUN_TEST(test_level_load_first);
    RUN_TEST(test_level_load_by_name);
    RUN_TEST(test_level_load_nonexistent);
    RUN_TEST(test_level_entity_positions);
    RUN_TEST(test_level_entity_source_rects);
    RUN_TEST(test_level_child_entities_instantiated);
    RUN_TEST(test_level_child_entity_positions);
    RUN_TEST(test_level_child_entity_tags);
    RUN_TEST(test_level_nested_children);

    RUN_TEST(test_flag_set_and_get);
    RUN_TEST(test_flag_clear);
    RUN_TEST(test_flag_unset_returns_false);
    RUN_TEST(test_flag_set_idempotent);
    RUN_TEST(test_flag_clear_nonexistent);
    RUN_TEST(test_trigger_parse_interact);
    RUN_TEST(test_trigger_parse_enter);
    RUN_TEST(test_trigger_parse_on_spawn);
    RUN_TEST(test_trigger_parse_event);
    RUN_TEST(test_trigger_parse_attr_changed);
    RUN_TEST(test_trigger_parse_unknown);
    RUN_TEST(test_condition_parse_flag);
    RUN_TEST(test_condition_parse_not_flag);
    RUN_TEST(test_condition_parse_attr_truthy);
    RUN_TEST(test_condition_parse_attr_short_form);
    RUN_TEST(test_condition_parse_not_attr);
    RUN_TEST(test_condition_parse_attr_less_than);
    RUN_TEST(test_condition_parse_attr_greater_than);
    RUN_TEST(test_condition_parse_attr_equals);
    RUN_TEST(test_condition_parse_has_item);
    RUN_TEST(test_condition_parse_unknown);
    RUN_TEST(test_action_parse_set_flag);
    RUN_TEST(test_action_parse_clear_flag);
    RUN_TEST(test_action_parse_set_attr);
    RUN_TEST(test_action_parse_add_attr);
    RUN_TEST(test_action_parse_toggle_attr);
    RUN_TEST(test_action_parse_destroy);
    RUN_TEST(test_action_parse_fire_event);
    RUN_TEST(test_action_parse_unknown);
    RUN_TEST(test_trigger_matches_simple);
    RUN_TEST(test_trigger_no_match_different_type);
    RUN_TEST(test_trigger_matches_event_with_argument);
    RUN_TEST(test_trigger_no_match_event_wrong_argument);
    RUN_TEST(test_condition_flag_true);
    RUN_TEST(test_condition_flag_false);
    RUN_TEST(test_condition_not_flag);
    RUN_TEST(test_condition_attr_truthy);
    RUN_TEST(test_condition_attr_falsy);
    RUN_TEST(test_condition_attr_missing);
    RUN_TEST(test_condition_attr_less_than);
    RUN_TEST(test_condition_attr_greater_than);
    RUN_TEST(test_condition_and_logic_all_pass);
    RUN_TEST(test_condition_and_logic_one_fails);
    RUN_TEST(test_action_set_flag_executes);
    RUN_TEST(test_action_clear_flag_executes);
    RUN_TEST(test_action_set_attr_bool);
    RUN_TEST(test_action_set_attr_int);
    RUN_TEST(test_action_add_attr);
    RUN_TEST(test_action_toggle_attr);
    RUN_TEST(test_action_destroy);
    RUN_TEST(test_action_fire_event_queues);
    RUN_TEST(test_action_execution_order);
    RUN_TEST(test_rules_parse_from_toml);
    RUN_TEST(test_rules_parse_no_rules);
    RUN_TEST(test_rules_parse_multiple_rules);
    RUN_TEST(test_evaluate_interact_sets_flag);
    RUN_TEST(test_evaluate_condition_blocks_action);
    RUN_TEST(test_evaluate_fire_event_cascading);
    RUN_TEST(test_integration_interact_rule);
    RUN_TEST(test_integration_condition_blocks_interact);
    RUN_TEST(test_integration_for_each_no_bind_iterates_all_entities);
    RUN_TEST(test_integration_for_each_condition_filter);
    RUN_TEST(test_integration_for_each_bind_mode);
    RUN_TEST(test_integration_subroutine_call);
    RUN_TEST(test_integration_subroutine_inherits_self);
    RUN_TEST(test_integration_subroutine_missing_is_soft_fail);
    RUN_TEST(test_integration_timer_oneshot_fires_once);
    RUN_TEST(test_integration_timer_periodic_fires_repeatedly);
    RUN_TEST(test_integration_timer_destroy_cancels);
    RUN_TEST(test_integration_on_destroy_fires);
    RUN_TEST(test_integration_defeat_fires_when_health_drops_to_zero);
    RUN_TEST(test_integration_collide_fires_on_overlap);
    RUN_TEST(test_var_set_local);
    RUN_TEST(test_var_set_global);
    RUN_TEST(test_var_condition_truthy);
    RUN_TEST(test_var_condition_falsy_when_unset);
    RUN_TEST(test_var_substitution_in_set_attr);
    RUN_TEST(test_local_var_scoped_per_rule);

    RUN_TEST(test_toml_str_content_is_copied);
    RUN_TEST(test_toml_str_datum_nulled_after_call);

    RUN_TEST(test_toml_emit_blueprints);
    RUN_TEST(test_toml_emit_level_with_entities);
    RUN_TEST(test_toml_emit_round_trip);
    RUN_TEST(test_toml_emit_buffer_too_small);
    RUN_TEST(test_toml_emit_no_music);
    RUN_TEST(test_toml_emit_blueprint_children);
    RUN_TEST(test_toml_emit_skips_child_entities);
    RUN_TEST(test_toml_emit_custom_attrs);
    RUN_TEST(test_toml_emit_health);
    RUN_TEST(test_toml_emit_rules);

    RUN_TEST(test_editor_radial_dead_zone_returns_negative_one);
    RUN_TEST(test_editor_radial_stick_up_four_items);
    RUN_TEST(test_editor_radial_stick_right_four_items);
    RUN_TEST(test_editor_radial_stick_down_four_items);
    RUN_TEST(test_editor_radial_stick_left_four_items);
    RUN_TEST(test_editor_radial_label_grab);
    RUN_TEST(test_editor_radial_label_delete);
    RUN_TEST(test_editor_radial_label_out_of_bounds);
    RUN_TEST(test_editor_word_builder_append_to_empty);
    RUN_TEST(test_editor_word_builder_append_with_underscore);
    RUN_TEST(test_editor_word_builder_append_overflow_noop);
    RUN_TEST(test_editor_word_builder_append_multiple);
    RUN_TEST(test_editor_word_builder_pop_last_word);
    RUN_TEST(test_editor_word_builder_pop_single_word);
    RUN_TEST(test_editor_word_builder_pop_empty_noop);
    RUN_TEST(test_editor_word_builder_total_count_no_blueprints);
    RUN_TEST(test_editor_word_builder_total_count_with_blueprints);
    RUN_TEST(test_editor_word_builder_item_zero_is_done);
    RUN_TEST(test_editor_word_builder_item_first_builtin);
    RUN_TEST(test_editor_word_builder_item_blueprint_name);
    RUN_TEST(test_editor_word_builder_item_negative_index);
    RUN_TEST(test_editor_place_visible_count_known_height);
    RUN_TEST(test_editor_place_visible_count_small_height);
    RUN_TEST(test_editor_total_attr_count_instance_only);
    RUN_TEST(test_editor_total_attr_count_with_blueprint);
    RUN_TEST(test_editor_is_blueprint_attr_false_for_instance);
    RUN_TEST(test_editor_is_blueprint_attr_true_for_blueprint);
    RUN_TEST(test_editor_find_nearest_single_entity);
    RUN_TEST(test_editor_find_nearest_closer_wins);
    RUN_TEST(test_editor_find_nearest_skips_children);
    RUN_TEST(test_editor_find_nearest_empty_level);
    RUN_TEST(test_editor_entity_outline_rect_with_collision);
    RUN_TEST(test_editor_entity_outline_rect_without_collision);
    RUN_TEST(test_editor_find_blueprint_by_name_found);
    RUN_TEST(test_editor_find_blueprint_by_name_not_found);
    RUN_TEST(test_editor_find_blueprint_by_name_empty_table);
    RUN_TEST(test_editor_mark_deleted_root_marks_child);
    RUN_TEST(test_editor_mark_deleted_chain);
    RUN_TEST(test_editor_mark_deleted_sibling_untouched);
    RUN_TEST(test_editor_apply_attr_delta_int);
    RUN_TEST(test_editor_apply_attr_delta_float);
    RUN_TEST(test_editor_apply_attr_delta_null_attr_no_crash);
    RUN_TEST(test_editor_attr_at_display_index_instance);
    RUN_TEST(test_editor_attr_at_display_index_blueprint);
    RUN_TEST(test_editor_attr_at_display_index_out_of_range);
    RUN_TEST(test_editor_toggle_pressed_key);
    RUN_TEST(test_editor_toggle_pressed_gamepad);
    RUN_TEST(test_editor_toggle_pressed_neither);
    RUN_TEST(test_editor_read_value_delta_no_input);
    RUN_TEST(test_editor_read_value_delta_large_minus);
    RUN_TEST(test_editor_read_value_delta_large_plus);
    RUN_TEST(test_editor_read_value_delta_huge_minus);
    RUN_TEST(test_editor_read_value_delta_combined);
    RUN_TEST(test_editor_read_held_dir_left_key);
    RUN_TEST(test_editor_read_held_dir_right_gamepad);
    RUN_TEST(test_editor_read_held_dir_none);
    RUN_TEST(test_editor_word_builder_nav_up);
    RUN_TEST(test_editor_word_builder_nav_up_clamped);
    RUN_TEST(test_editor_word_builder_nav_down);
    RUN_TEST(test_editor_word_builder_nav_down_clamped);
    RUN_TEST(test_editor_word_builder_nav_page_up);
    RUN_TEST(test_editor_word_builder_nav_page_down);

    return UNITY_END();
}
